version: '3.8'

#nginx
services:
  webserver:
    image: nginx:stable-alpine
    container_name: lcp_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/ 
      - ./dockerize/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laraveldockerize

 
#mysql services 
  mysql:
    image: mysql:8.0.21
    container_name: lcp_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    volumes:
      - ./dockerize/mysql:/var/lib/mysql
      - ./dockerize/mysql:/my.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

    networks:
      - laraveldockerize

#php services 
  php:
    build: 
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laraveldockerize

#composer Services

  composer:
    image: composer:latest
    container_name: lcp_composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
      -php
    networks:
      - laraveldockerize

#npm
  npm:
    image: node:14.9
    container_name: lcp_npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

#artisan services
  artisan:
    build:
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    container_name: lcp_artisan
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', /var/www/html/artisan]   
    networks:
      - laraveldockerize   

networks:
  laraveldockerize:


